//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelecomDataBase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comanda
    {
        public int Id { get; set; }
        public int IdProdus { get; set; }
        public int IdClient { get; set; }
        public int Cantitate { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Comanda Comanda1 { get; set; }
        public virtual Comanda Comanda2 { get; set; }
        public virtual Produ Produ { get; set; }
    }
}
